apiVersion: v1
kind: Secret
metadata:
  name: github-app-credentials
  namespace: {{ .Values.runner.namespace }}
type: Opaque
data:
  APP_LOGIN: {{ .Values.secrets.APP_LOGIN }}
  APP_ID: {{ .Values.secrets.APP_ID }}
  INSTALLATION_ID: {{ .Values.secrets.INSTALLATION_ID }}
  APP_PRIVATE_KEY: {{ .Values.secrets.APP_PRIVATE_KEY }}