apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
  namespace: training
  labels:
    app: github-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-runner
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: github-runner  
    spec:
      serviceAccountName: github-runner
      containers:
        - name: github-runner
          image: myoung34/github-runner:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: RUNNER_SCOPE
              value: "org"  
            - name: ORG_NAME
              value: "yggdrasilcorp" 
            - name: RUNNER_WORKDIR
              valueFrom:
                configMapKeyRef:
                  key: RUNNER_WORKDIR
                  name: github-runner-config
            - name: APP_ID
              valueFrom:
                secretKeyRef:
                  key: APP_ID
                  name: github-app-credentials
            - name: APP_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  key: APP_PRIVATE_KEY
                  name: github-app-credentials
            - name: INSTALLATION_ID
              valueFrom:
                secretKeyRef:
                  key: INSTALLATION_ID
                  name: github-app-credentials
            - name: APP_LOGIN
              valueFrom:
                secretKeyRef:
                  key: APP_LOGIN
                  name: github-app-credentials
          volumeMounts:
            - mountPath: /home/runner/_work
              name: workspace
            - mountPath: /start.sh
              name: github-runner-script
              subPath: start.sh
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 500Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir: {}
          name: workspace
        - name: github-runner-script
          configMap:
            name: github-runner-config
            items:
              - key: start.sh
                path: start.sh